string user_id      # legacy
string trace_id
string mode         # legacy: video or photo

int8 change_zoom

int8 change_shutter_speed
int8 change_f_stop
int8 change_iso
int8 change_iso_auto                # -1:no auto, 0:no change, 1:activate change

int8 change_exposure_bias
int8 change_white_balance
int8 change_white_balance_auto      # -1:no auto, 0:no change, 1:activate change

# only thermal camera
int8 change_thermal_range_maximum
int8 change_thermal_range_minimum
string change_thermal_mode			# AUTO, MANUAL, SPAN
int8 change_thermal_palette		# GREY

string exposure_mode                # P, A, S, M

bool default_auto_focus
int16 focus_point_x
int16 focus_point_y
string focus_size                   # SMALL, MEDIUM, LARGE, WIDE
---
bool command_executed