string user_id
string trace_id
bool clear_interval # When this parameter is set allother parameters are ignored and the last set interval is cleared
string path
string filetype # The file ending for the picture file. Determines how it is saved (e.g. jpg/png/etc...)
bool distance_interval # When this is false a time interval is used. When it is true a photo is trigered after a specific ground distance.
int32 interval_value # When distance_interval false unit is seconds, when distance_interval true unit is m.
---
bool interval_set